### ISSUE TITLE
gpu-index misidentifying gpu's

### ISSUE THREAD

**Issue by DeFlanko** [xnorpx/blue-onyx#37]
I think the gpu-index is being misidentified, for example:

![image](https://github.com/user-attachments/assets/f8506c0f-7aa4-48dc-a0e4-9a9695ccea0b)

![image](https://github.com/user-attachments/assets/087613e1-a38e-471b-b421-e6bcf11c302c)

and all bat files are currnetly set to:

```bat
--gpu-index 0
```

**Comment by xnorpx** [comment]
That does indeed look funky, will mark this as a bug and take a look.

**Comment by DeFlanko** [comment]
im experimenting with a user input box to have them select their GPU and then that value be put into the bat file... i'll update my pull once i have something that is working right... Currently its doing funky stuff there as well...

**Comment by DeFlanko** [comment]
so i think i have a fix in PR: https://github.com/xnorpx/blue-onyx/pull/36 

this is a big assumption but i think Task Manager's index of GPU's is Alphabetical.  When i was testing with 
```powershell
Get-CimInstance Win32_VideoController | Select-Object Name
```

The output would put the NVIDA gpu first. where in Task Manager its "Second". 

So hopfully adding the  `Sort-Obect Name` fixes that. 

also added in logic to remove the RDP Display adapter from being in the list... this might need tweeking and further testing but it worked for me. 

```powershell
Get-CimInstance Win32_VideoController | Select-Object Name | Where-Object name -NotMatch "Microsoft Remote Display Adapter" |Sort-Object Name
```

**Comment by DeFlanko** [comment]
so i think i have a fix in PR: https://github.com/xnorpx/blue-onyx/pull/36 

this is a big assumption but i think Task Manager's index of GPU's is Alphabetical.  When i was testing with 
```powershell
Get-CimInstance Win32_VideoController | Select-Object Name
```

The output would put the NVIDA gpu first. where in Task Manager its "Second". 

So hopefully adding the  `Sort-Object Name` fixes that. 

also added in logic to remove the RDP Display adapter from being in the list... this might need tweaking and further testing but it worked for me. 

```powershell
Get-CimInstance Win32_VideoController | Select-Object Name | Where-Object name -NotMatch "Microsoft Remote Display Adapter" |Sort-Object Name
```

**Comment by xnorpx** [comment]
So the query I do in code is from the DirectX API.

Can you test with GPU index and see if 0 and 1 coming from the log or from task manager is correct.

i.e. when you select 0 do you use Intel or Nvidia, when you select 1 do you use Intel or Nvidia.

**Comment by DeFlanko** [comment]
When i select 0 it was Intel, when i select 1 it was Nvidia.

**Comment by xnorpx** [comment]
Ok let me sort the gpu list

**Comment by xnorpx** [comment]
I pushed a change in #52 I leave this one open until I do a new release and you can check it.

**Comment by DeFlanko** [comment]
This is resolve in 0.5.0 ! Closing.
